### Ответ 1

```js

function task(callback) {
  
  setTimeout(() => {
    callback()
    console.log('Task completed');  
  }, 2000);
}

function onCompleted() {
  console.log('All tasks completed')
}

task(onCompleted);
```

### Ответ 2

```js

function firstTask() {

  return new Promise((resolve, reject) => {

  setTimeout(() => {

    if (Math.random() > 0.5) {
      resolve('First task completed');

    } else {
      reject('Error');
    };
  }, 2000);
  });
}
```

### Ответ 3

```js

function firstTask() {

  return new Promise(resolve => {

  setTimeout(() => {
    const value = 5;
    resolve(value)
  }, 2000);
  });
};

function secondTask(valueFromFirstTask) {

  return new Promise(resolve => {
    
  setTimeout(() => {
    const value = valueFromFirstTask * 10;
    resolve(value)
  }, 2000);
  });
};
firstTask().then(valueFromFirstTask => secondTask(valueFromFirstTask)).then(console.log); 
```

### Ответ 4

```js

const firstResponse = new Promise(resolve => setTimeout(() => resolve({id: 1}), 2000));
const secondResponse = new Promise(resolve => setTimeout(() => resolve({id: 2}), 3000));
const thirdResponse = new Promise(resolve => setTimeout(() => resolve({id: 3}), 1000));

Promise.all([
  firstResponse,
  secondResponse, 
  thirdResponse
]).then(console.log);
```

### Ответ 5

```js

function toPromise(arg) {

  return new Promise(resolve => resolve(arg));

};

function toPromise(arg) {

  return Promise.resolve(arg);

};
```

### Ответ 6

```

1. Promise.all – ожидает выполнения всех промисов и возвращает массив с результатами. Если любой из указанных промисов вернёт ошибку, то результатом работы Promise.all будет эта ошибка, результаты остальных промисов будут игнорироваться.
2. Promise.race – ожидает первый выполненный промис, который становится его результатом, остальные игнорируются.
3. Promise.allSettled(promises) (добавлен недавно) – ждёт, пока все промисы завершатся и возвращает их результаты в виде массива с объектами, у каждого объекта два свойства:
state: "fulfilled", если выполнен успешно или "rejected", если ошибка,
value – результат, если успешно или reason – ошибка, если нет.
```